package:
  name: artiq
  version: {{ environ["GIT_DESCRIBE_TAG"] }}

source:
  git_url: ../..

{% set data = load_setup_py_data() %}

build:
  noarch: python
  number: {{ environ["GIT_DESCRIBE_NUMBER"] }}
  string: {{ environ["GIT_DESCRIBE_NUMBER"] }}+git{{ environ["GIT_FULL_HASH"][:8] }}
  entry_points:
    # NOTE: conda-build cannot distinguish between console and gui scripts
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}
  ignore_prefix_files: True

requirements:
  build:
    - python >=3.5.3,<3.6
    - setuptools 33.1.1
  run:
    - python >=3.5.3,<3.6
    - llvmlite-artiq 0.23.0.dev py35_4
    - binutils-or1k-linux >=2.27
    - pythonparser >=1.1
    - openocd 0.10.0 6
    - lit
    - outputcheck
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - h5py 2.8
    - python-dateutil
    - pyqt >=5.5
    - quamash
    - pyqtgraph 0.10.0
    - pygit2
    - aiohttp
    - levenshtein

test:
  imports:
    - artiq

about:
  home: https://m-labs.hk/artiq
  license: LGPL
  summary: 'ARTIQ (Advanced Real-Time Infrastructure for Quantum physics) is a next-generation control system for quantum information experiments. It is being developed in partnership with the Ion Storage Group at NIST, and its applicability reaches beyond ion trapping.'
