package:
  name: artiq-board
  version: {{ environ["GIT_DESCRIBE_TAG"] }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ["GIT_DESCRIBE_NUMBER"] }}
  string: {{ environ["GIT_DESCRIBE_NUMBER"] }}+git{{ environ["GIT_FULL_HASH"][:8] }}
  script_env:
    - ARTIQ_TARGET
    - ARTIQ_VARIANT
  ignore_prefix_files: True

outputs:
  - name: artiq-{{ environ["ARTIQ_TARGET"] }}-{{ environ["ARTIQ_VARIANT"] }}
    noarch: python
    files:
      - site-packages
    requirements:
      run:
        - artiq {{ "{tag} {number}+git{hash}".format(tag=environ["GIT_DESCRIBE_TAG"], number=environ["GIT_DESCRIBE_NUMBER"], hash=environ["GIT_FULL_HASH"][:8]) }}
    ignore_prefix_files: True

requirements:
  build:
    - artiq-dev {{ "{tag} {number}+git{hash}".format(tag=environ["GIT_DESCRIBE_TAG"], number=environ["GIT_DESCRIBE_NUMBER"], hash=environ["GIT_FULL_HASH"][:8]) }}

about:
  home: https://m-labs.hk/artiq
  license: LGPL
  summary: 'Bitstream, BIOS and firmware for the {{ environ.get("ARTIQ_TARGET") }}-{{ environ.get("ARTIQ_VARIANT") }} board variant'
